language: python
python: 
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  

install:
  - pip install numpy
  - pip install pandas
  - pip install codecov
  - pip install pytest-cov
  - pip install .

# run tests
script:
  - python -m pytest --cov tests-python/

after_success:
  - codecov